import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NewNav from './Components/NewNav'; 
import Footer from './Footer'; 

import MinistryMaterial from './Components/MinistryMaterial'; 


// import Footer from './Components/'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
    {/* Add in the Navbar here  */}
    {/* <NewNav/>  */}
      <body className={inter.className}>
      
      {children}
      
      <MinistryMaterial/> 
      
      
      
      </body>
      {/* Add in the footer here  */}
      {/* <Footer/>  */}
      
      
    </html>
  )
}
